services:  
  - type: web
    name: elysiajs-hello-world
    runtime: node
    repo: https://github.com/Anishali2/elysiajs-store 
    plan: free
    envVars:
    - key: BUN_VERSION
      value: 1.1.0
    region: oregon
    buildCommand: bun install
    startCommand: bun start
version: "1"
